# mocha-done-issue

An example project showing that mocha does not recognize exceptions once done has been called.